dist: trusty
language: java
jdk:
    - oraclejdk8
sudo: false

# Databases
addons:
    mariadb: '10.1'
services: 
    - postgresql
before_script:
      - psql -c 'create database pextest;' -U postgres
      - mysql -u root -e 'create database pextest;'
script:
    - mvn install

cache:
    directories:
        - $HOME/.m2

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "permissionsex-bukkit/target/*.jar"
  on:
    tags: true
