language: java

jdk:
  - openjdk8
  - openjdk12

cache:
  directories:
    - $HOME/.gradle # Gradle build cache

before_install: chmod +x ./gradlew

jobs:
  include:
    - stage: deploy
      script: ./gradlew publish

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "permissionsex-bukkit/target/*.jar"
  on:
    all_branches: true
